<a href="https://colab.research.google.com/github/gsgill7/gsgill7/blob/main/Exercises/07%20Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Make NumPy available:

In [2]:
import numpy as np

## Exercise 07.1 (indexing and timing)

Create two very long NumPy 1D-arrays (vectors) `x` and `y` and sum the arrays using:

1. The NumPy addition syntax, `z = x + y`; and
2. A `for` loop that computes the sum entry-by-entry

Compare the time required for the two approaches for arrays of different lengths (use a very long array for
the timing). The values of the array entries are not important for this test. Use `%time` to report the time.

*Hint:* To loop over an array using indices, try a construction like:

In [ ]:
x = np.ones(10)
y = np.ones(len(x))
for i in range(len(x)):
    print(x[i]*y[i])

#### (1) Add two arrays using built-in addition operator:

In [9]:
x = np.random.rand(1000000)
y = np.random.rand(1000000)
%time z = x+y

CPU times: user 2.87 ms, sys: 977 µs, total: 3.85 ms
Wall time: 3.86 ms


#### (2) Add two arrays using own implementation:

In [8]:
x = np.random.rand(1000000)
y = np.random.rand(1000000)

def add_arrays(x,y):
  z=[]
  for i in range(len(x)):
      z.append(x[i] + y[i])
  return z
%time z = add_arrays(x,y)



CPU times: user 418 ms, sys: 32.6 ms, total: 450 ms
Wall time: 465 ms


### Optional extension: just-in-time (JIT) compilation

You will see a large difference in the time required between your NumPy and 'plain' Python implementations. This is due to Python being an *interpreted* language as opposed to a *compiled* language. A way to speed up plain Python implementions is to convert the interpreted Python code into compiled code. A tool for doing this is [Numba](https://numba.pydata.org/).

Below is an example using Numba and JIT to accelerate a computation:

In [6]:
!pip -q install numba
import numba
import numpy as np
import math

@numba.jit
def add_arrays(x,y):
  z=[]
  for i in range(len(x)):
      z.append(x[i] + y[i])
  return z


x = np.random.rand(10000000)
y = np.random.rand(10000000)
%time z = x+y
%time z = add_arrays(x,y)

CPU times: user 10.8 ms, sys: 28 ms, total: 38.9 ms
Wall time: 38.8 ms
CPU times: user 629 ms, sys: 336 ms, total: 965 ms
Wall time: 958 ms


**Task:** Test if Numba can be used to accelerate your implementation that uses indexing to sum two arrays, and by how much.

In [7]:
!pip -q install numba
import numba
import numpy as np
import math

@numba.jit
def add_arrays(x,y):
  z=[]
  for i in range(len(x)):
      z.append(x[i] + y[i])
  return z


x = np.random.rand(10000000)
y = np.random.rand(10000000)
%time z = x+y
%time z = add_arrays(x,y)

CPU times: user 31.4 ms, sys: 8.87 ms, total: 40.2 ms
Wall time: 40.3 ms
CPU times: user 492 ms, sys: 336 ms, total: 828 ms
Wall time: 910 ms


## Exercise 07.2 (member functions and slicing)

Anonymised scores (out of 60) for an examination are stored in a NumPy array. Write:

1. A function that takes a NumPy array of the raw scores and returns the scores as percentages, sorted from
   lowest to highest (try using `scores.sort()`, where `scores` is a NumPy array holding the scores).
1. A function that returns the maximum, minimum and mean of the raw scores as a dictionary with the
   keys '`min`', '`max`' and '`mean`'. Use the NumPy array functions `min()`, `max()` and `mean()` to do the
   computation, e.g. `max = scores.max()`.  
   
   Design your function for the min, max and mean to optionally exclude the highest and lowest scores from the
   computation of the min, max and mean.
   
   *Hint:* sort the array of scores and use array slicing to exclude
   the first and the last entries.

Use the scores
```python
scores = np.array([58.0, 35.0, 24.0, 42, 7.8])
```
to test your functions.

In [10]:
def to_percentage_and_sort(scores):
    percentages = scores / 60 * 100
    percentages.sort()
    return percentages

def statistics(scores, exclude=False):
    if exclude:
        scores = scores[1:-1]
    else:
        scores = scores
    return {"min": scores.min(), "max": scores.max(), "mean": scores.mean()}

In [11]:
## tests ##

scores = np.array([58.0, 35.0, 24.0, 42, 7.8])
assert np.isclose(to_percentage_and_sort(scores), [ 13.0, 40.0, 58.33333333,  70.0, 96.66666667]).all()

s0 = statistics(scores)
assert np.isclose(s0["min"], 7.8)
assert np.isclose(s0["mean"], 33.36)
assert np.isclose(s0["max"], 58.0)

s1 = statistics(scores, True)
assert np.isclose(s1["min"], 24.0)
assert np.isclose(s1["mean"], 33.666666666666666667)
assert np.isclose(s1["max"], 42.0)

## Exercise 07.3 (slicing)

For the two-dimensional array

In [13]:
A = np.array([[4.0, 7.0, -2.43, 67.1],
             [-4.0, 64.0, 54.7, -3.33],
             [2.43, 23.2, 3.64, 4.11],
             [1.2, 2.5, -113.2, 323.22]])
print(A)

[[   4.      7.     -2.43   67.1 ]
 [  -4.     64.     54.7    -3.33]
 [   2.43   23.2     3.64    4.11]
 [   1.2     2.5  -113.2   323.22]]


use array slicing for the below operations, printing the results to the screen to check. Try to use array slicing such that your code would still work if the dimensions of `A` were enlarged.

**Check your results carefully against hand computations.**

#### 1. Extract the third column as a 1D array

In [14]:
x = np.zeros(4)
for i in range(len(A)):
  x[i]=A[i][2]
print(x)

[  -2.43   54.7     3.64 -113.2 ]


#### 2. Extract the first two rows as a 2D sub-array

In [16]:
x=A[0:2]
print(x)


[[ 4.    7.   -2.43 67.1 ]
 [-4.   64.   54.7  -3.33]]


#### 3.  Extract the bottom-right $2 \times 2$ block as a 2D sub-array

In [18]:
x=A[2:4,2:4]
print(x)

[]


#### 4. Sum the last column

In [20]:
x=0
for i in A:
  x+=i[3]
print(x)

391.1


#### Compute transpose

Compute the transpose of `A` (search online to find the function/syntax to do this).

In [22]:
x=np.transpose(A)
print(x)

[[   4.     -4.      2.43    1.2 ]
 [   7.     64.     23.2     2.5 ]
 [  -2.43   54.7     3.64 -113.2 ]
 [  67.1    -3.33    4.11  323.22]]


## Exercise 07.4 (optional extension)

In a previous exercise you implemented the bisection algorithm to find approximate roots of a mathematical function. Use the SciPy bisection function `optimize.bisect` (https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.bisect.html) to find roots of the mathematical function that was used in the previous exercise. Compare the results computed by SciPy and your program from the earlier exercise, and compare the computational time (using `%time`).

In [ ]:
from scipy import optimize

...